# Create a project release automatically on tag creation

name: create_release_on_tag

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4`

jobs:
  build:
    name: create_release_on_tag
    runs-on: ubuntu-latest
    permissions:
      repository-projects: write

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2.3.3
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set up Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.17.13
        id: go

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: 'v1.6.1'
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

